# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8075

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/yak_java?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: yak_sql
    password: yak_sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO